apiVersion: v1
kind: ConfigMap
metadata:
  name: minion-config 
  labels:
    app: {{ .Values.OpenNMS.Minion.ServiceName }}
  namespace: {{ .Release.Namespace }}
data:
  grpc-config: |
    grpc.max.message.size=104857600
    # Properties below override these defined earlier in file!
    {{- range $Key, $Value := .Values.OpenNMS.Minion.GrpcConfig }}
    {{ $Key }}={{ $Value }}
    {{- end }}
  opennms-minion-identity: |
    id=${env:HOSTNAME:-UNKNOWN}
    location=${env:LOCATION:-Default}
