spring:
  application:
    name: horizon-stream-inventory

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: db/changelog/changelog.xml

  kafka:
    consumer:
      group-id: "inventory"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    bootstrap-servers: localhost:59092

grpc:
  server:
    port: 6565
    deadline: 60000

  client:
    minion-gateway:
      host: opennms-minion-gateway
      port: 8991
      tlsEnabled: false
      maxMessageSize: 10485760

kafka:
  topics:
    minion-heartbeat: "heartbeat"
    task-set-results: "task-set.results"
    internal-events: "internal-event"
    node: "node"


keycloak:
  realm: opennms
  base-url: http://onms-keycloak:8080/auth

inventory:
  azure:
    login-url: https://login.microsoftonline.com
    management-url: https://management.azure.com
    api-version: 2021-04-01
    metrics-api-version: 2018-01-01

management:
  endpoints:
    web:
      exposure:
        include: "*"
