{{ if .Values.Kafka.Enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: {{ .Values.Kafka.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.Kafka.Port }}
      name: client
      protocol: TCP
      targetPort: {{ .Values.Kafka.Port }}
    - port: {{ .Values.Kafka.ControllerPort }}
      name: controller
      protocol: TCP
      targetPort: {{ .Values.Kafka.ControllerPort }}
  selector:
    app: {{ .Values.Kafka.ServiceName }}
  type: ClusterIP
{{ end }}
