apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.Notification.ServiceName }}
  labels:
    app: {{ .Values.OpenNMS.Notification.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.OpenNMS.Notification.ServiceName }}
  replicas: {{ .Values.OpenNMS.Notification.Replicas }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.OpenNMS.Notification.ServiceName }}
    spec:
      {{- if .Values.NodeRestrictions.Enabled }}
      nodeSelector:                                                                                    
        {{ .Values.NodeRestrictions.Key }}: {{ .Values.NodeRestrictions.Value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.NodeRestrictions.Key }}"                                                    
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.NodeRestrictions.Key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.NodeRestrictions.Value }}                                                 
      {{- end }}
      containers:
        - name: {{ .Values.OpenNMS.Notification.ServiceName }}
          image: {{ .Values.OpenNMS.Notification.Image }}
          imagePullPolicy: {{ .Values.OpenNMS.Notification.ImagePullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y"  # FIXME: Permanent debug port, enable only for dev mode
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.Kafka.Host }}:{{ .Values.Kafka.Port }}"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/notification"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: notificationUser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: notificationPwd
            - name: HORIZON_KEYCLOAK_BASE_URL
              value: "http://{{ .Values.Keycloak.ServiceName }}:{{ .Values.Keycloak.Port }}{{ .Values.Keycloak.Path }}/"
            - name: HORIZON_KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.Keycloak.ServiceName }}-initial-admin
                  key: username
            - name: HORIZON_KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.Keycloak.ServiceName }}-initial-admin
                  key: password
          ports:
            - name: grpc
              containerPort: {{ .Values.OpenNMS.Notification.GrpcPort }}
      {{- if .Values.OpenNMS.Notification.PrivateRepoEnabled }}
      imagePullSecrets:
        - name: image-credentials
      {{- end }}
