spring:
  application:
    name: horizon-stream-alert

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/alert
    username: alert
    password: passw0rd

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: db/changelog/changelog.xml

  kafka:
    template:
      default-topic: "alerts"
    consumer:
      client-id: "alert-service"
      group-id: "alert"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      client-id: "alert-service"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "*"

keycloak:
  realm: opennms
  base-url: http://onms-keycloak:8080/auth
  public-key: ""

grpc:
  server:
    port: 6565
    deadline: 60000

kafka:
  topics:
    alert-events: "events"
    new-alerts: "alerts"
    node-changed: "node"
    monitoring-policy: "monitoring-policy"
    tag-operation: "tag-operation"
